### ISSUE TITLE
Should this module always return POSIX-style paths?

### ISSUE THREAD

**Issue by phated** [jonschlinkert/to-absolute-glob#4]
I was trying to remove the path normalization in glob-stream because node-glob **only** deals in POSIX-style paths but found that our `base` property is always normalized based on platform due to the use of node's `path` module here.

I think this could be changed by using https://www.npmjs.com/package/path-posix instead.  Thoughts?

**Comment by phated** [comment]
After poking at it, I'm not sure `path-posix` will work due to the `process.cwd()` usage.  It might require a path separator regexp replacer.

**Comment by phated** [comment]
Maybe just use this impl? https://github.com/isaacs/node-glob/blob/master/common.js#L198-L214

**Comment by jonschlinkert** [comment]
(sorry I didn't see this issue when I commented on the AppVeyor issue)

K, I'll take a look in a few

**Comment by jonschlinkert** [comment]
related https://github.com/jonschlinkert/is-absolute/blob/master/index.js

Ok, after a quick glance, I know I've implemented that code somewhere. I might have a module that does exactly that, or I might have implemented that on a local branch for this, but I remember doing it. 

In the meantime feel free to add to the list if you think of anything else - I think we just need to nail down what the expectations of this module are and implement against those requirements.

**Comment by jonschlinkert** [comment]
@phated fwiw I won't be online part of the day but if possible I'm going to try to do this today.

**Comment by phated** [comment]
Thanks. I'm holding off on someone other glob-stream changes until this stuff gets sorted. I think being consistent with node-glob is a good idea.

**Comment by jonschlinkert** [comment]
> I'm holding off on someone other glob-stream changes until this stuff gets sorted

no problem, these are easy changes. I'm still offline but wanted to let you know I saw this

**Comment by jonschlinkert** [comment]
k, I wasn't able to get online much the past 24 hrs or so. I'm back on. I'll work on this asap.

Edit: @phated are there any specific issues you can point to that glob-stream is having so I can try to make sure they're passing with any changes I make? 

just thinking out loud, I'm going to list some things that come to mind that I'm assuming we need to be sensitive to, mainly to get your consensus/clarification of what the main goals are:
- ~~posix-style paths (just to make 100% sure, do you mean "posix-style" as another way of saying "unix-style"? Or do you want to explicitly support posix-specific double slashes at the beginning of paths? Honestly I don't think it makes a difference, since posix and unix paths are the same in every other way and single/double leading slashes will probably be treated the same in node-glob and by node path. just my 2c)~~ nvm, this is irrelevant. I've spent too much time reading path spec stuff lately. I keep forgetting that node `path` refers to them as posix paths, so when you said posix I was thinking you meant something other than what node does... anyway ignore this
- `changedCwd`: Is this relevant here? Just to talk through it... in node-glob, this option essentially tracks whether or not a path was changed from what was specified by the user, so that if we absolutify a path - and the user specified a relative path - we can re-relative the path when it's returned. If we did want to support this, I think this option would make more sense in glob-stream, since this lib should always be returning an absolute glob (I'd be happy to help with the path logic in glob-stream too)

Other than that I think these are pretty simple changes. Let me know if I'm missing something else.

**Comment by phated** [comment]
I don't know where `changedCwd` came from.  I have no need for it.

I still think these problems need to be worked through, but I've also opened https://github.com/isaacs/node-glob/pull/293 as a possible solution to absolute paths as `glob-stream` uses them

**Comment by jonschlinkert** [comment]
> I still think these problems need to be worked through

What issue were you having? are there failing unit tests I can look at or help with? 

If there is something we need to do here I'd be happy to implement it. If the fix in node-glob does the trick, that's great too. 

edit:

> I don't know where changedCwd came from. I have no need for it.

that was in the code you pointed to on node-glob.

**Comment by phated** [comment]
This logic doesn't seem to work on Windows: https://github.com/jonschlinkert/to-absolute-glob/blob/master/index.js#L17 because it is checking for `/` at `char(0)`.  I think it needs to use https://github.com/sindresorhus/path-is-absolute

Also, it is normalizing paths on Windows to `\\` but node-glob deals exclusively in `/` separator because it uses `\\` as an escape character.

**Comment by phated** [comment]
These things (and probably others I can't see right now) are why the tests need to be run on (and some written for) Windows.

**Comment by jonschlinkert** [comment]
> This logic doesn't seem to work on Windows

fwiw, this was initially from https://github.com/gulpjs/glob-stream/pull/55, I mentioned some of this in the pr comment. I guess this is the feedback I was asking for. 

> but node-glob deals exclusively in / separator because it uses \ as an escape character.

yeah it looks like node-glob needs to be updated too, since it does the same check for `char(0)` and `/` [here](https://github.com/isaacs/node-glob/blob/master/glob.js#L691), before unixifying the [leading slash later](https://github.com/isaacs/node-glob/blob/master/glob.js#L701). 

> I think it needs to use https://github.com/sindresorhus/path-is-absolute

no problem, I brought this up as well in [this comment](https://github.com/gulpjs/glob-stream/pull/53#issuecomment-153910522) (I'm not sure if path-is-absolute existed at the time. looks like the same thing as [is-absolute](https://github.com/jonschlinkert/is-absolute))

> These things (and probably others I can't see right now) are why the tests need to be run on (and some written for) Windows.

We're implementing appveyor and will make sure to add additional tests for windows paths.

**Comment by phated** [comment]
Both at the node-glob line you linked and https://github.com/isaacs/node-glob/blob/master/common.js#L198-L214, there are separate paths for `isAbsolute` and slash at char 0.

**Comment by phated** [comment]
Sorry I'm just noticing these things now.  I've never dug into glob-stream or node-glob before.  This stuff has always been a black box to me (and I've relied to heavily on the not-quite-good-enough tests).

**Comment by jonschlinkert** [comment]
no worries. I usually go overboard with tests, I have no problem adding a lot more tests here if it helps give peace of mind.

I think the solution here is to do what you're suggesting, and unixify the paths and use isAbsolute [here](https://github.com/jonschlinkert/to-absolute-glob/blob/master/index.js#L19-L21) following the same logic as node-glob. 

Does that sound right to you? if so I can get that started

**Comment by phated** [comment]
I still don't fully grasp everything between this library and the `makeAbs` utility method of node-glob.  I'd say give it a go and I'll drop it into some local branches I have been working on.

**Comment by jonschlinkert** [comment]
no problem, that's fine with me. I'll get started then we can discuss and you can do what makes sense for node-glob based on that

**Comment by jonschlinkert** [comment]
@phated related [pr here](https://github.com/jonschlinkert/to-absolute-glob/pull/7)

**Comment by doowb** [comment]
@jonschlinkert @phated the PRs have been merged and changes published as `2.0.0`. Can we close this issue?

**Comment by jonschlinkert** [comment]
yes, I believe so. I'll close but we can reopen if necessary

**Comment by phated** [comment]
🎉  you both rock!
